library(shiny)
library(shinydashboard)
library(shinyjs)
library(DT)
library(plotly)

options(shiny.maxRequestSize = 1000 * 1024^2) # 100 MB

source("~/Desktop/Institut_Cochin/Code/CARROT/pipeline_cytometrie.R")
source("~/Desktop/Institut_Cochin/Code/CARROT/R/module_import.R.R")
source("~/Desktop/Institut_Cochin/Code/CARROT/R/utils.R")
source("~/Desktop/Institut_Cochin/Code/CARROT/R/module_compensation.R")
source("~/Desktop/Institut_Cochin/Code/CARROT/R/module_demixage.R")
source("~/Desktop/Institut_Cochin/Code/CARROT/R/module_qc.R")
source("~/Desktop/Institut_Cochin/Code/CARROT/R/module_pretraitement.R")
source("~/Desktop/Institut_Cochin/Code/CARROT/R/module_analyse.R")


CANAUX_CONNUS <- c(
  "", 
  "7-AAD", 
  "Alexa Fluor 350-A", 
  "Alexa Fluor 405-A",
  "Alexa Fluor 488-A",
  "Alexa Fluor 532-A",
  "Alexa Fluor 546-A",
  "Alexa Fluor 568-A",
  "Alexa Fluor 594-A",
  "Alexa Fluor 647-A",
  "Alexa Fluor 660-A",
  "Alexa Fluor 680-A",
  "Alexa Fluor 700-A",
  "AmCyan-A",
  "APC-A",
  "APC-Cy5.5-A",
  "APC-Cy7-A",
  "APC-eFluor 780-A",
  "APC-Fire 750-A",
  "APC-Fire 810-A",
  "APC-H7-A",
  "APC-R700-A",
  "APC-Vio770-A",
  "BB515-A",
  "BB630-A",
  "BB660-A",
  "BB700-A",
  "BB755-A",
  "BB790-A",
  "BUV395-A",
  "BUV496-A",
  "BUV563-A",
  "BUV615-A",
  "BUV661-A",
  "BUV737-A",
  "BUV805-A",
  "BV 421-A",
  "BV 480-A",
  "BV 510-A",
  "BV 570-A",
  "BV 605-A",
  "BV 650-A",
  "BV 711-A",
  "BV 750-A",
  "BV 786-A",
  "BV 805-A",
  "DyLight 680-A",
  "DyLight 800-A",
  "DAPI-A",
  "eFluor 450-A",
  "eFluor 506-A",
  "eFluor 660-A",
  "eFluor 780-A",
  "FITC-A",
  "GFP-A",
  "KIRAVIA Blue 520-A",
  "Live-Dead Blue-A",
  "mCherry-A",
  "NovaFluor Blue 510-A",
  "NovaFluor Blue 530-A",
  "NovaFluor Blue 555-A",
  "NovaFluor Blue 585-A",
  "NovaFluor Blue 610-30S-A",
  "NovaFluor Blue 610-70S-A",
  "NovaFluor Blue 660-120S-A",
  "NovaFluor Blue 660-40S-A",
  "NovaFluor Blue 690-A",
  "NovaFluor Blue 725-A",
  "NovaFluor Blue 760-A",
  "NovaFluor Blue 800-A",
  "NovaFluor Red 660-A",
  "NovaFluor Red 685-A",
  "NovaFluor Red 700-A",
  "NovaFluor Red 710-A",
  "NovaFluor Red 725-A",
  "NovaFluor Red 755-A",
  "NovaFluor UV 765-A",
  "NovaFluor Violet 690-A",
  "NovaFluor Violet 745-A",
  "NovaFluor Violet 800-A",
  "NovaFluor Yellow 570-A",
  "NovaFluor Yellow 590-A",
  "NovaFluor Yellow 610-A",
  "NovaFluor Yellow 660-A",
  "NovaFluor Yellow 690-A",
  "NovaFluor Yellow 700-A",
  "NovaFluor Yellow 730-A",
  "NovaFluor Yellow 755-A",
  "NovaFluor Yellow 810-A",
  "Pacific Blue-A",
  "Pacific Orange-A",
  "PE-A",
  "PE-Alexa Fluor 610-A",
  "PE-Alexa Fluor 700-A",
  "PE-CF594-A",
  "PE-Cy5-A",
  "PE-Cy5.5-A",
  "PE-Cy7-A",
  "PE-Dazzle 594-A",
  "PE-eFluor 610-A",
  "PE-Fire 640-A",
  "PE-Fire 700-A",
  "PE-Fire 744-A",
  "PE-Fire 810-A",
  "PerCP-A",
  "PerCP-Cy5-5-A",
  "PerCP-eFluor 710-A",
  "PerCP-Fire 780-A",
  "PerCP-Fire 806-A",
  "PE-Texas Red-A",
  "PE-Vio770-A",
  "Qdot 525-A",
  "Qdot 545-A",
  "Qdot 565-A",
  "Qdot 585-A",
  "Qdot 605-A",
  "Qdot 625-A",
  "Qdot 655-A",
  "Qdot 705-A",
  "Qdot 800-A",
  "R718-A",
  "RB545-A",
  "RB575-A",
  "RB613-A",
  "RB670-A",
  "RB705-A",
  "RB744-A",
  "RB780-A",
  "RB824-A",
  "RFP-A",
  "RR688-A",
  "RV544-A",
  "RV828-A",
  "RY586-A",
  "RY610-A",
  "RY655-A",
  "RY703-A",
  "RY743-A",
  "RY775-A",
  "SBB580-A",
  "SBB615-A",
  "SBB675-A",
  "SBB700-A",
  "SBB765-A",
  "SBB810-A",
  "SBR670-A",
  "SBR715-A",
  "SBR775-A",
  "SBR815-A",
  "SBUV400-A",
  "SBUV445-A",
  "SBUV510-A",
  "SBUV540-A",
  "SBUV575-A",
  "SBUV605-A",
  "SBUV665-A",
  "SBUV700-A",
  "SBUV740-A",
  "SBUV770-A",
  "SBUV795-A",
  "SBV440-A",
  "SBV475-A",
  "SBV515-A",
  "SBV535-A",
  "SBV570-A",
  "SBV610-A",
  "SBV670-A",
  "SBV710-A",
  "SBV760-A",
  "SBV790-A",
  "SBY575-A",
  "SBY605-A",
  "SBY665-A",
  "SBY720-A",
  "SBY800-A",
  "Spark Blue 515-A",
  "Spark Blue 550-A",
  "Spark Blue 574-A",
  "Spark PLUS Blue 574-A",
  "Spark NIR 685-A",
  "Spark PLUS B550-A",
  "Spark PLUS UV 395-A",
  "Spark Red 718-A",
  "Spark UV 387-A",
  "Spark UV 395-A",
  "Spark Violet 423-A",
  "Spark PLUS V475-A",
  "Spark Violet 500-A",
  "Spark Violet 538-A",
  "Spark YG 570-A",
  "Spark YG 581-A",
  "Spark YG 593-A",
  "Super Bright 436-A",
  "Super Bright 600-A",
  "Super Bright 645-A",
  "Super Bright 702-A",
  "Super Bright 780-A",
  "V450-A",
  "V500-A",
  "V547-A",
  "ViaKrome 808-A",
  "VioBright FITC-A",
  "YFP-A",
  "Zombie NIR-A",
  "Zombie Aqua-A",
  "Zombie UV-A",
  "Hoechst-A",
  "CF350-A",
  "CF405S-A",
  "CF405M-A",
  "CF405L-A",
  "CF430-A",
  "CF440-A",
  "CF450-A",
  "CF488A-A",
  "CF503R-A",
  "CF514-A",
  "CF532-A",
  "CF543-A",
  "CF550R-A",
  "CF555-A",
  "CF568-A",
  "CF570-A",
  "CF583-A",
  "CF594-A",
  "CF620R-A",
  "CF633-A",
  "CF640R-A",
  "CF647-A",
  "CF660C-A",
  "CF660R-A",
  "CF680-A",
  "CF680R-A",
  "CF700-A",
  "CF710-A",
  "CF725-A",
  "CF740-A",
  "CF750-A",
  "CF770-A",
  "CF790-A",
  "CF800-A",
  "mFluor Vio610-A",
  "Alexa Fluor 514-A",
  "Alexa Fluor 555-A",
  "Alexa Fluor 610-A",
  "Alexa Fluor 633-A",
  "Alexa Fluor 790-A",
  "TRITC-A",
  "Texas Red-A",
  "Cy3-A",
  "Cy5-A",
  "Cy5.5-A",
  "Cy7-A",
  "BV570-T-A",
  "LIVE/DEAD Aqua-A",
  "LIVE/DEAD Blue-A",
  "LIVE/DEAD Fixable Near-IR-A",
  "Fixable Viability Dye eFluor 450-A",
  "Fixable Viability Dye eFluor 506-A",
  "Fixable Viability Dye eFluor 520-A",
  "Propidium Iodide-A",
  "FSV440UV-A",
  "FVS450-A",
  "FVS510-A",
  "FSV520-A",
  "FSV570-A",
  "FVS575V-A",
  "FVS620-A",
  "FVS660-A",
  "FVS700-A",
  "FVS780-A",
  "Zombie Green-A",
  "Zombie Aqua-A",
  "Zombie Red-A",
  "Zombie Violet-A",
  "Zombie Yellow-A",
  "CellTrace Violet-A",
  "CellTrace CFSE-A",
  "CellTrace Far Red-A",
  "CellTrace Yellow-A",
  "CellTrace Oregon Green-A",
  "CellTrace Red-A",
  "CellTrace Blue-A",
  "CellTrace Calcein Blue-A",
  "CellTrace Calcein AM-A",
  "EdU Alexa 647-A",
  "EdU Alexa 488-A",
  "BrDU FITC-A",
  "DRAQ5-A",
  "DRAQ7-A",
  "SYTOX Green-A",
  "SYTOX Blue-A",
  "SYTOX Red-A",
  "SYTOX Orange-A",
  "SYTO 9-A",
  "mTagBFP2-A",
  "mKate2-A",
  "mScarlet-A",
  "mOrange-A",
  "Keima-A",
  "iRFP670-A",
  "iRFP720-A",
  "miRFP670-A",
  "miRFP703-A",
  "mNeonGreen-A",
  "EBFP-A",
  "Turquoise-A",
  "ECFP-A",
  "EYFP-A",
  "mCitrine-A",
  "tdTomato-A",
  "mRuby-A",
  "mPlum-A",
  "APC-Vio750-A",
  "PE-Vio615-A",
  "VioBright B515-A",
  "VioBright V600-A",
  "cFluor UV450-A",
  "cFluor UV610-A",
  "cFluor V450-A",
  "cFluor V500-A",
  "cFluor V610-A",
  "cFluor V650-A",
  "cFluor V710-A",
  "cFluor V785-A",
  "cFluor B513-A",
  "cFluor B548-A",
  "cFluor B610-A",
  "cFluor B660-A",
  "cFluor B710-A",
  "cFluor B760-A",
  "cFluor YG580-A",
  "cFluor YG610-A",
  "cFluor YG667-A",
  "cFluor YG720-A",
  "cFluor YG780-A",
  "cFluor R659-A",
  "cFluor R685-A",
  "cFluor R720-A",
  "cFluor R775-A",
  "cFluor R840-A",
  "Viobility 488-520-A",
  "Viobility 405-520-A",
  "Viobility 640-770-A",
  "Viobility 405-452-A",
  "Ghost Red 710-A",
  "Ghost Blue 516-A",
  "Ghost Red 780-A",
  "Ghost UV 450-A",
  "Ghost Violet 450-A",
  "Ghost Violet 510-A",
  "Ghost Violet 540-A"
)


ui <- dashboardPage(
  skin = "purple",
  dashboardHeader(title = "CARROT"),
  dashboardSidebar(
    sidebarMenu(
      id = "tabs_sidebar",
      menuItem("Importation",    tabName = "import_tab",       icon = icon("file-import")),
      menuItem("Compensation",   tabName = "compensation_tab", icon = icon("calculator")),
      menuItem("Unmixing",       tabName = "unmixing_tab",     icon = icon("bolt")),
      menuItem("Quality Control",tabName = "nettoyage_tab",    icon = icon("broom")),
      menuItem("Prétraitement",  tabName = "pretraitement_tab",icon = icon("filter")),
      menuItem("Analyses",       tabName = "analyses_tab",     icon = icon("chart-pie"))
    )
  ),
  dashboardBody(
    useShinyjs(),
    tags$head(tags$style(HTML("
      .datatables, .dataTables_wrapper, table.dataTable tbody td { color: black !important; }
      .disabled-tab  { pointer-events: none; opacity: 0.4; }
      .btn-purple    { color: white; background-color: #605ca8; border-color: #555299; }
    "))),
    tabItems(
      tabItem(tabName = "import_tab",
              import_data_ui("mon_module_import")),
      tabItem(tabName = "compensation_tab",
              compensation_ui("mon_module_comp")),
      tabItem(tabName = "nettoyage_tab",
              qc_ui("mon_module_qc")),
      tabItem(tabName = "pretraitement_tab",
              pretraitement_ui("mon_module_pretrait")),
      tabItem(tabName = "unmixing_tab",  
              demixage_ui("mon_module_demixage")),
      tabItem(tabName = "analyses_tab",
              analyse_ui("mon_module_analyse"))
    )
  )
)

server <- function(input, output, session) {
  
  # ── Deux reactiveVal partagés entre les modules ──
  my_pipeline         <- reactiveVal(CARROT$new())
  my_pipeline_version <- reactiveVal(0L)          # s'incrémente après charger_fcs()
  
  import_data_server("mon_module_import",
                     pipeline  = my_pipeline,
                     pipeline_version = my_pipeline_version,
                     canaux = CANAUX_CONNUS)
  
  compensation_server("mon_module_comp",
                      pipeline         = my_pipeline,
                      pipeline_version = my_pipeline_version)
  
  demixage_server("mon_module_demixage",
                  pipeline         = my_pipeline,
                  pipeline_version = my_pipeline_version)
  
  qc_server("mon_module_qc",
            pipeline         = my_pipeline,
            pipeline_version = my_pipeline_version)
  
  pretraitement_server("mon_module_pretrait",
                       pipeline         = my_pipeline,
                       pipeline_version = my_pipeline_version)
  
  analyse_server("mon_module_analyse",
                 pipeline         = my_pipeline,
                 pipeline_version = my_pipeline_version)
}

shinyApp(ui, server)